function syncViewportHeight(){const h=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--app-height',`${Math.round(h)}px`)}syncViewportHeight();addEventListener('resize',syncViewportHeight);addEventListener('orientationchange',()=>setTimeout(syncViewportHeight,180));window.visualViewport?.addEventListener('resize',syncViewportHeight);
const animals={bear:{name:'반달가슴곰',img:'#img-bear',video:'video-bear',w:1.12,h:1.0,msg:'조용하고 깨끗한 숲이 나의 집이에요.'},deer:{name:'노루',img:'#img-deer',video:'video-deer',w:.88,h:1.0,msg:'풀과 나무가 있는 안전한 숲이 좋아요.'},otter:{name:'수달',img:'#img-otter',video:'video-otter',w:.72,h:1.0,msg:'맑은 물과 안전한 물가가 필요해요.'}};
const $=s=>document.querySelector(s);let selected='bear';let videoMode=false;let markerVisible=false;
const status=$('#status-pill'), start=$('#start-screen'), imagePlane=$('#animal-image'), videoPlane=$('#animal-video'), label=$('#marker-label'), card=$('#animal-card');
function setStatus(t){status.textContent=t}function stopVideos(){Object.values(animals).forEach(a=>{const v=document.getElementById(a.video);if(v){v.pause();}})}
function updateButtons(){document.querySelectorAll('[data-select]').forEach(b=>b.classList.toggle('active',b.dataset.select===selected))}
function applyAnimal(){const a=animals[selected];label.setAttribute('value',a.name);imagePlane.setAttribute('src',a.img);imagePlane.setAttribute('width',a.w);imagePlane.setAttribute('height',a.h);videoPlane.setAttribute('width',a.w);videoPlane.setAttribute('height',a.h);$('#animal-name').textContent=a.name;$('#animal-message').textContent=a.msg;updateButtons();if(markerVisible)showSelected();}
async function showSelected(){const a=animals[selected];card.classList.remove('hidden');label.setAttribute('value',a.name);if(videoMode){imagePlane.setAttribute('visible','false');videoPlane.setAttribute('visible','true');videoPlane.setAttribute('src','#'+a.video);stopVideos();const v=document.getElementById(a.video);try{v.currentTime=0;await v.play();setStatus(`${a.name} 영상이 나타났어요.`)}catch(e){console.warn(e);videoMode=false;$('#mode-button').textContent='사진 모드';imagePlane.setAttribute('visible','true');videoPlane.setAttribute('visible','false');setStatus(`${a.name} 사진 모드로 나타났어요. 영상은 기기가 버거울 수 있어요.`)}}else{stopVideos();videoPlane.setAttribute('visible','false');imagePlane.setAttribute('visible','true');setStatus(`${a.name}이 나타났어요. 화면이 안정되면 영상 모드를 켜 보세요.`)}}
document.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.select;applyAnimal();setStatus(`${animals[selected].name} 선택됨. 공통마커를 비춰 주세요.`)}));
$('#mode-button').addEventListener('click',()=>{videoMode=!videoMode;$('#mode-button').textContent=videoMode?'영상 모드':'사진 모드';if(markerVisible)showSelected();else setStatus(videoMode?'영상 모드 선택됨. 공통마커를 비춰 주세요.':'사진 모드 선택됨. 공통마커를 비춰 주세요.')});
function enterAR(){const btn=document.querySelector('.a-enter-vr-button, .a-enter-ar-button, .a-enter-vr button, .a-enter-ar button');if(btn){try{btn.click()}catch(e){console.warn(e)}}}
$('#start-button').addEventListener('click',()=>{start.classList.add('hidden');setStatus('카메라가 켜지면 공통마커를 화면 가운데에 크게 비춰 주세요.');setTimeout(enterAR,250)});$('#manual-enter').addEventListener('click',()=>{enterAR();setStatus('공통마커를 화면 가운데에 크게 비춰 주세요.')});
const marker=$('#main-marker');marker.addEventListener('markerFound',()=>{markerVisible=true;showSelected()});marker.addEventListener('markerLost',()=>{markerVisible=false;card.classList.add('hidden');stopVideos();setStatus('공통마커를 다시 화면 가운데에 맞춰 주세요.')});
setTimeout(()=>{const scene=$('a-scene');if(scene){scene.addEventListener('camera-init',()=>setStatus('카메라가 켜졌어요. 공통마커를 비춰 주세요.'));scene.addEventListener('camera-error',()=>setStatus('카메라 오류예요. Chrome 카메라 권한을 확인해 주세요.'))}},100);applyAnimal();
